on: 
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Api/CustomerAccountApi.csproj --configuration Release --output ./publish

    - name: Get latest code
      uses: actions/setup-dotnet@v2

    - name: Upload ftp
      uses: hsimah/ftp-action-delete-first@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ./publish/
        remoteDir: customerapi/
        options: "--delete --asci"

    #- name: Sync Files
    #  uses: SamKirkland/FTP-Deploy-Action@4.3.2
    #  with:
    #    server: ${{ secrets.ftp_server }}
    #    username: ${{ secrets.ftp_user }}
    #    password: ${{ secrets.ftp_password }}
    #    dangerous-clean-slate: true
    #    local-dir: ./publish/
    #    server-dir: customerapi/
